[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200

lib_deps =
  m5stack/M5Unified
  m5stack/M5CoreS3
  adafruit/Adafruit NeoPixel
  https://github.com/m5stack/M5Module-HMI.git
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.4
  lvgl/lvgl@^9.2.0

build_flags = 
  -I lib/display
  -I lib/pages
  -I lib/widgets
  -I lib/ui
  -I include
  -I fonts
  -I img
  -D LV_CONF_INCLUDE_SIMPLE
  -D DEVICE_ID="${PLATFORMIO_BUILD_FLAGS}"

build_src_filter = 
  +<*>
  +<../fonts/*.c>
  +<../include/*.c>
  +<../img/*.c>
